#!/bin/bash

DOCKER_IMAGE_FULL_NAME=280666639932.dkr.ecr.us-west-2.amazonaws.com/iadea.service.$((cat /etc/aws.ec2.instance.name) | tr '[:upper:]' '[:lower:]').v1:latest

REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
REGION=${REGION:0:-1}

source <(curl -s https://zeus.1adea.com/api/iCare.safeServer.awsKey?region=${REGION})

yum install -y docker
service docker start
aws ecr get-login --no-include-email | sh

docker pull $DOCKER_IMAGE_FULL_NAME
docker run --rm -p 80:80 $DOCKER_IMAGE_FULL_NAME
